list: $/pensoft/survey/models/recipient/columns.yaml
modelClass: Pensoft\Survey\Models\Recipient
title: Recipients
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/survey/recipients/update/:id'
